### ISSUE TITLE
[docs] user may not have `make` installed, rendering toolchain unusable

### ISSUE THREAD

**Issue by lifehackerhansol** [WonderfulToolchain/wf-issues#9]
While unlikely if you know how to write code in general, it is possible that a user may not have `make` installed. This does not come with Wonderful Toolchain, and is neither present in the installation instructions nor anywhere else on the docs. (My use case for W-T is BlocksDS, though the wswan target likely has the same issue given the templates also use `make`).
- Note that devkitPro's APT package for devkitpro-pacman actually lists `make` as a dependency, making it a non-issue at least on Debian-based systems when people install that. Though by design and choice, W-T doesn't, nor wants to, install this way.

This is especially noticeable for a user that may not have touched Linux ever in their life and set up WSL2 purely out of interest for this toolchain; for instance, I had to reinstall my WSL2 distro today due to hardware issues, and found that Microsoft's Ubuntu image does not have either `make` nor `build-essential` installed.

Maybe some note about relevant packages to install would be a good idea (i.e. "Please go to Google and search how to install these particular applications for your Linux distribution.") It's the kind of thing that a LMGTFY would solve, but IMO such a note would change the situation from "figuring it out while debugging why I'm missing this" to "figuring it out since the docs told me I need this".

**Comment by asiekierka** [comment]
https://github.com/WonderfulToolchain/wonderful-docs/commit/a648ff7f2567178e48e6e7c9df6fca9d6a303207

Fixed, thank you!
